# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luís Sousa
tagline:          luish
description:      Some random texts
url:              http://luish.github.com

author:
  name:           Luis Henrique Sousa
  url:            https://luish.github.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/luish/luish.github.io

pages_list:
    About:   '/about'
    Posts:   '/posts'
    Feed:    '/atom.xml'

social_list:
  GitHub: 'http://github.com/luish'
  Twitter: 'http://twitter.com/luishborges'
  Instagram: 'https://www.instagram.com/luish.borges/'
  LinkedIn: 'https://linkedin.com/in/luishborges'