# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Luis Henrique Borges
tagline:          luish
description:      Some random texts
url:              http://luish.github.com

author:
  name:           Luis Henrique Borges
  url:            https://twitter.com/luishborges

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/luish/luish.github.io

pages_list:
    Github:  'http://github.com/luish'
    Twitter: 'http://twitter.com/luishborges'
    Instagram: 'http://instagram.com/luish.borges'
    LinkedIn: 'http://br.linkedin.com/in/luishborges'
    #Sobre:   '/sobre'
    #Posts:   '/posts'
    #Feed:    '/atom.xml'
